### PR TITLE
remove nix types from public api

### LINKED ISSUE #100: `nix` in public API
I think it is better not to expose `nix` types in the public API, such as `RecvConn::can_read_from_source`.

1. `nix` is an implementation detail.
2. Currently updating `nix` to a new incompatible version requires a new incompatible release of `rustbus`.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
(hopefully) Closes #100

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Irrelevant, but why does `RecvConn::can_read_from_source` exist? 1. It can be easily implemented by a client, using poll, select, or any other poll-like function of choice. 2. Why is it needed if the same can be achieved using a non-blocking `get_next_message`?

**Comment by KillingSpark** [comment]
> why does `RecvConn::can_read_from_source` exist?

I think this just predated exposing the raw filedescriptor to clients.

> Why is it needed if the same can be achieved using a non-blocking get_next_message?

Is that the same? A non-blocking `get_next_message` could make no progress or progress but not enough to actually read a complete message without the caller able to tell which one happened right?

**Comment by MaxVerevkin** [comment]
> Is that the same? A non-blocking `get_next_message` could make no progress or progress but not enough to actually read a complete message without the caller able to tell which one happened right?

Sure. But does it matter?

**Comment by KillingSpark** [comment]
> Sure. But does it matter?

It is the difference between a client that is just very slow and a client that opens a connection, sends a partial message and then never sends anything again. Depending on how much you trust your services you may want to kill the connection to the latter but not to the former

**Comment by MaxVerevkin** [comment]
> It is the difference between a client that is just very slow and a client that opens a connection, sends a partial message and then never sends anything again. 

I don't think I follow. Why is sending partial messages related to `get_next_message`?

**Comment by KillingSpark** [comment]
The scenario I am thinking about is this:

* A service using rustbus calling `get_next_message`
* A client X that is either malicious or just buggy sent a partial message and then stopped
* A client Y that is very slow sending small chunks at a time but will finish the complete message at some point

The service might want to kill a connection to X after a certain time but maintain the connection to Y. The difference is that Y is making progress just very slowly while X is not doing anything useful, instead it is using up ressources in the service.

**Comment by MaxVerevkin** [comment]
Ah, okay, I see. But surely such a service would poll a set of fds and not ever call `can_read_from_source`.

**Comment by KillingSpark** [comment]
Oh yeah they definitely should! But as I said this was the crutch I thought of before just exposing the raw fd and I guess it survived up until now. Could be marked as deprecated though.

**Pull request merged**
