### PR TITLE
Add get_fds() to MarshalledMessageBody

### PR DESCRIPTION
**Pull request by cmaves**
Also derive some additional useful traits for simple types.

### CODE REVIEW

**Comment by KillingSpark** [comment]
This seems like a useful tool. The doc comment does not match the behaviour though. The `None => break;` Should be an error instead. `None` signals that the unixfd has already been taken.

To be honest it might be better to change the dup() signature to use only a `Result` and convert the `Option<_>` from the `UnixInnerFd::get` into a new Error case in [this function](https://github.com/KillingSpark/rustbus/blob/b6d24b5b9470ee79723b8d3680ea757d9a6b32e0/rustbus/src/wire/unixfd.rs#L58).

This way the meaning of the returned value is easier to match against and the semantics are more clear. 

Mixing Option and Result in the return type is likely to cause these kinds of issues, which I should have thought about when writing this.

**Comment by cmaves** [comment]
I've been thinking about this, and I think this function should just clone Vec<UnixFd> rather than even try to dup it. The important thing is that the fds can be accessed at all. What people decide to do with them can just be left up to the end user.

**Comment by KillingSpark** [comment]
That would be fine too. Duping all of them is probably unnecessary overhead for most users.

**Comment by cmaves** [comment]
This PR now only clones the Fds.

**Pull request merged**
